coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 1.0%
        paths:
          - "Sources"
    changes:
      default:
        threshold: 1.0%
        paths:
          - "Sources"
    patch: off

comment:
  layout: "flags, files"
  behavior: new
  after_n_builds: 3

ignore:
  - Tests/**/*
  - Pods/**/*
  - Scripts/**/*
