codecov:
  notify:
    after_n_builds: 3

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 1.0%
    patch:
      default:
        threshold: 10.0%
    changes:
      default:
        threshold: 1.0%

comment:
  layout: "flags, files"
  behavior: new
  after_n_builds: 3

ignore:
  - Tests
  - Pods
  - Scripts
